//////////////////////////////////////////////////////////////////////////////
// Model: dpp.qm
// File:  ././dpp.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#ifndef dpp_h
#define dpp_h

#include "qp_port.h"
#include "modbus-mgr.h"

namespace Zebra {

enum ZebraSignals {
    EAT_SIG = QP::Q_USER_SIG, // published by Table to let a philosopher eat
    DONE_SIG,                 // published by Philosopher when done eating
    PAUSE_SIG,                // published by BSP to pause the application
    TERMINATE_SIG,            // published by BSP to terminate the application
    MAX_PUB_SIG,              // the last published signal

    HUNGRY_SIG,               // posted direclty to Table from hungry Philo
    MAX_SIG                   // the last signal
};

// @(/1/0) ...................................................................
class TableEvt : public QP::QEvt {
public:
    uint8_t philoNum;
};


extern QP::QActive * const AO_Modbus;

}                             // namespace Zebra

#endif                        // dpp_h
